### ISSUE TITLE
License should be specified.

### ISSUE THREAD

**Issue by lionirdeadman** [TheAndroidMaster/Crasher#7]
I can't seem to find the license for this code anywhere meaning that technically anyone using it is violating your copyright and shouldn't be using it. 

Would you mind putting a license (I'd use LGPL personnally)?

**Comment by fennifith** [comment]
Huh, you're right. I usually add one before I publish it. Guess I missed this one.

FYI, I believe that bintray does distribute copies under the specified license (apache-2.0 if I remember correctly) so you wouldn't be violating anything by using that, just the actual contents of the repo.

I'll add a license and update this sometime tomorrow. It's late here, and despite most programmer stereotypes I do actually need to sleep (lol)

**Comment by lionirdeadman** [comment]
Haha. It's fine. No worries. 

I noticed because the license didn't show up in Alarmio.
